name: flutter_clean_architecture_getx
description: 'A new Flutter project.'
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.3
  flutter_dotenv: ^6.0.0
  flutter_secure_storage: ^9.2.4
  logger: ^2.6.2
  package_info_plus: ^9.0.0
  dartz: ^0.10.1
  equatable: ^2.0.7
  intl: ^0.20.2
  dio: ^5.9.0
  pretty_dio_logger: ^1.4.0
  flutter_svg: ^2.2.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/svgs/

flutter_native_splash:
  color: "#ffffff"
  android: true
  ios: true



#dart run flutter_launcher_icons
#flutter pub run flutter_native_splash:create
#rename setAppName --targets ios,android,web,macos,windows,linux --value "Money Track"
#rename setBundleId --targets ios,android,macos,linux,windows --value "com.chowdhuryelab.money_track"
#find lib -type f -name "*.dart" -exec sed -i '' 's/package:flutter_clean_architecture_getx\//package:flutter_clean_architecture_getx\//g' {} +